import { Injectable } from '@nestjs/common';
import { Roles } from 'src/entities/roles.entity';
import { DataSource } from "typeorm";

import { Generos } from 'src/entities/generos.entity';
import { Usuarios } from 'src/entities/usuarios.entity';
import { UsuariosDetalle } from 'src/entities/usuarios_detalle.entity';
import { Paises } from 'src/entities/paises.entity';
import * as bcrypt from 'bcrypt';
import { TipoReporte } from 'src/entities/tipo.reporte.entity';

@Injectable()
export class DatabaseSeederService {
  private readonly roleRepository;
  private readonly generoRepository;
  private readonly usuarioRepository;
  private readonly usuarioDetalleRepository;
  private readonly paisRepository;
  private readonly tipoReportes;

  constructor(private readonly connection: DataSource) {
    this.roleRepository = this.connection.getRepository(Roles);
    this.generoRepository = this.connection.getRepository(Generos);
    this.usuarioRepository = this.connection.getRepository(Usuarios);
    this.usuarioDetalleRepository =
      this.connection.getRepository(UsuariosDetalle);
    this.paisRepository = this.connection.getRepository(Paises);
    this.tipoReportes = this.connection.getRepository(TipoReporte);

  }

  async seed() {
    const synchronize = process.env.ormConfig_synchronize === 'true';
    if (synchronize) {
      await this.deleteDB();
      
      await this.seedPaises();
      await this.seedRoles();
      await this.seedGeneros();
      await this.seedAdminUser();
      await this.seedTiposReportes();
    }
  }

  private async deleteDB() {

    await this.connection.dropDatabase();
    await this.connection.synchronize();

  }

  private async seedRoles() {
    const roles = [
      { id: 1, descripcion: 'Administrador del sistema' },
      { id: 2, descripcion: 'Usuario normal' },
    ];
    await this.roleRepository.save(roles);
  }

  private async seedGeneros() {
    const generos = [
      { descripcion: 'Masculino' },
      { descripcion: 'Femenino' },
      { descripcion: 'Indefinido' },
    ];
    await this.generoRepository.save(generos);
  }

  private async seedPaises() {
    const paises = [
      {
        id: 1,
        nombre: 'Afganistán',
        nombrecorto: 'AFG',
        codigopais: 'AFG',
        codigotelefono: '+93',
        foto: 'https://flagcdn.com/160x120/af.png',
      },
      {
        id: 2,
        nombre: 'Albania',
        nombrecorto: 'ALB',
        codigopais: 'ALB',
        codigotelefono: '+355',
        foto: 'https://flagcdn.com/160x120/al.png',
      },
      {
        id: 3,
        nombre: 'Alemania',
        nombrecorto: 'DEU',
        codigopais: 'DEU',
        codigotelefono: '+49',
        foto: 'https://flagcdn.com/160x120/de.png',
      },
      {
        id: 4,
        nombre: 'Andorra',
        nombrecorto: 'AND',
        codigopais: 'AND',
        codigotelefono: '+376',
        foto: 'https://flagcdn.com/160x120/ad.png',
      },
      {
        id: 5,
        nombre: 'Angola',
        nombrecorto: 'AGO',
        codigopais: 'AGO',
        codigotelefono: '+244',
        foto: 'https://flagcdn.com/160x120/ao.png',
      },
      {
        id: 6,
        nombre: 'Anguila',
        nombrecorto: 'AIA',
        codigopais: 'AIA',
        codigotelefono: '+1 264',
        foto: 'https://flagcdn.com/160x120/ai.png',
      },
      {
        id: 7,
        nombre: 'Antigua y Barbuda',
        nombrecorto: 'ATG',
        codigopais: 'ATG',
        codigotelefono: '+1 268',
        foto: 'https://flagcdn.com/160x120/ag.png',
      },
      {
        id: 8,
        nombre: 'Arabia Saudita',
        nombrecorto: 'SAU',
        codigopais: 'SAU',
        codigotelefono: '+966',
        foto: 'https://flagcdn.com/160x120/sa.png',
      },
      {
        id: 9,
        nombre: 'Argelia',
        nombrecorto: 'DZA',
        codigopais: 'DZA',
        codigotelefono: '+213',
        foto: 'https://flagcdn.com/160x120/dz.png',
      },
      {
        id: 10,
        nombre: 'Argentina',
        nombrecorto: 'ARG',
        codigopais: 'ARG',
        codigotelefono: '+54',
        foto: 'https://flagcdn.com/160x120/ar.png',
      },
      {
        id: 11,
        nombre: 'Armenia',
        nombrecorto: 'ARM',
        codigopais: 'ARM',
        codigotelefono: '+374',
        foto: 'https://flagcdn.com/160x120/am.png',
      },
      {
        id: 12,
        nombre: 'Aruba',
        nombrecorto: 'ABW',
        codigopais: 'ABW',
        codigotelefono: '+297',
        foto: 'https://flagcdn.com/160x120/aw.png',
      },
      {
        id: 13,
        nombre: 'Australia',
        nombrecorto: 'AUS',
        codigopais: 'AUS',
        codigotelefono: '+61',
        foto: 'https://flagcdn.com/160x120/au.png',
      },
      {
        id: 14,
        nombre: 'Austria',
        nombrecorto: 'AUT',
        codigopais: 'AUT',
        codigotelefono: '+43',
        foto: 'https://flagcdn.com/160x120/at.png',
      },
      {
        id: 15,
        nombre: 'Azerbaiyán',
        nombrecorto: 'AZE',
        codigopais: 'AZE',
        codigotelefono: '+994',
        foto: 'https://flagcdn.com/160x120/az.png',
      },
      {
        id: 16,
        nombre: 'Bahamas',
        nombrecorto: 'BHS',
        codigopais: 'BHS',
        codigotelefono: '+1 242',
        foto: 'https://flagcdn.com/160x120/bs.png',
      },
      {
        id: 17,
        nombre: 'Bahrein',
        nombrecorto: 'BHR',
        codigopais: 'BHR',
        codigotelefono: '+973',
        foto: 'https://flagcdn.com/160x120/bh.png',
      },
      {
        id: 18,
        nombre: 'Bangladesh',
        nombrecorto: 'BGD',
        codigopais: 'BGD',
        codigotelefono: '+880',
        foto: 'https://flagcdn.com/160x120/bd.png',
      },
      {
        id: 19,
        nombre: 'Barbados',
        nombrecorto: 'BRB',
        codigopais: 'BRB',
        codigotelefono: '+1 246',
        foto: 'https://flagcdn.com/160x120/bb.png',
      },
      {
        id: 20,
        nombre: 'Belarús',
        nombrecorto: 'BLR',
        codigopais: 'BLR',
        codigotelefono: '+375',
        foto: 'https://flagcdn.com/160x120/by.png',
      },
      {
        id: 21,
        nombre: 'Bélgica',
        nombrecorto: 'BEL',
        codigopais: 'BEL',
        codigotelefono: '+32',
        foto: 'https://flagcdn.com/160x120/be.png',
      },
      {
        id: 22,
        nombre: 'Belice',
        nombrecorto: 'BLZ',
        codigopais: 'BLZ',
        codigotelefono: '+501',
        foto: 'https://flagcdn.com/160x120/bz.png',
      },
      {
        id: 23,
        nombre: 'Benín',
        nombrecorto: 'BEN',
        codigopais: 'BEN',
        codigotelefono: '+229',
        foto: 'https://flagcdn.com/160x120/bj.png',
      },
      {
        id: 24,
        nombre: 'Bermudas',
        nombrecorto: 'BMU',
        codigopais: 'BMU',
        codigotelefono: '+1 441',
        foto: 'https://flagcdn.com/160x120/bm.png',
      },
      {
        id: 25,
        nombre: 'Bhután',
        nombrecorto: 'BTN',
        codigopais: 'BTN',
        codigotelefono: '+975',
        foto: 'https://flagcdn.com/160x120/bt.png',
      },
      {
        id: 26,
        nombre: 'Bolivia',
        nombrecorto: 'BOL',
        codigopais: 'BOL',
        codigotelefono: '+591',
        foto: 'https://flagcdn.com/160x120/bo.png',
      },
      {
        id: 27,
        nombre: 'Bonaire',
        nombrecorto: 'BES',
        codigopais: 'BES',
        codigotelefono: '+5997',
        foto: 'https://flagcdn.com/160x120/bq.png',
      },
      {
        id: 28,
        nombre: 'Bosnia y Herzegovina',
        nombrecorto: 'BIH',
        codigopais: 'BIH',
        codigotelefono: '+387',
        foto: 'https://flagcdn.com/160x120/ba.png',
      },
      {
        id: 29,
        nombre: 'Botsuana',
        nombrecorto: 'BWA',
        codigopais: 'BWA',
        codigotelefono: '+267',
        foto: 'https://flagcdn.com/160x120/bw.png',
      },
      {
        id: 30,
        nombre: 'Brasil',
        nombrecorto: 'BRA',
        codigopais: 'BRA',
        codigotelefono: '+55',
        foto: 'https://flagcdn.com/160x120/br.png',
      },
      {
        id: 31,
        nombre: 'Brunéi Darussalam',
        nombrecorto: 'BRN',
        codigopais: 'BRN',
        codigotelefono: '+673',
        foto: 'https://flagcdn.com/160x120/bn.png',
      },
      {
        id: 32,
        nombre: 'Bulgaria',
        nombrecorto: 'BGR',
        codigopais: 'BGR',
        codigotelefono: '+359',
        foto: 'https://flagcdn.com/160x120/bg.png',
      },
      {
        id: 33,
        nombre: 'Burkina Faso',
        nombrecorto: 'BFA',
        codigopais: 'BFA',
        codigotelefono: '+226',
        foto: 'https://flagcdn.com/160x120/bf.png',
      },
      {
        id: 34,
        nombre: 'Burundi',
        nombrecorto: 'BDI',
        codigopais: 'BDI',
        codigotelefono: '+257',
        foto: 'https://flagcdn.com/160x120/bi.png',
      },
      {
        id: 35,
        nombre: 'Cabo Verde',
        nombrecorto: 'CPV',
        codigopais: 'CPV',
        codigotelefono: '+238',
        foto: 'https://flagcdn.com/160x120/cv.png',
      },
      {
        id: 36,
        nombre: 'Camboya',
        nombrecorto: 'KHM',
        codigopais: 'KHM',
        codigotelefono: '+855',
        foto: 'https://flagcdn.com/160x120/kh.png',
      },
      {
        id: 37,
        nombre: 'Camerún',
        nombrecorto: 'CMR',
        codigopais: 'CMR',
        codigotelefono: '+237',
        foto: 'https://flagcdn.com/160x120/cm.png',
      },
      {
        id: 38,
        nombre: 'Canadá',
        nombrecorto: 'CAN',
        codigopais: 'CAN',
        codigotelefono: '+1',
        foto: 'https://flagcdn.com/160x120/ca.png',
      },
      {
        id: 39,
        nombre: 'Chad',
        nombrecorto: 'TCD',
        codigopais: 'TCD',
        codigotelefono: '+235',
        foto: 'https://flagcdn.com/160x120/td.png',
      },
      {
        id: 40,
        nombre: 'Chile',
        nombrecorto: 'CHL',
        codigopais: 'CHL',
        codigotelefono: '+56',
        foto: 'https://flagcdn.com/160x120/cl.png',
      },
      {
        id: 41,
        nombre: 'China',
        nombrecorto: 'CHN',
        codigopais: 'CHN',
        codigotelefono: '+86',
        foto: 'https://flagcdn.com/160x120/cn.png',
      },
      {
        id: 42,
        nombre: 'Chipre',
        nombrecorto: 'CYP',
        codigopais: 'CYP',
        codigotelefono: '+357',
        foto: 'https://flagcdn.com/160x120/cy.png',
      },
      {
        id: 43,
        nombre: 'Ciudad del Vaticano',
        nombrecorto: 'VAT',
        codigopais: 'VAT',
        codigotelefono: '+39',
        foto: 'https://flagcdn.com/160x120/va.png',
      },
      {
        id: 44,
        nombre: 'Colombia',
        nombrecorto: 'COL',
        codigopais: 'COL',
        codigotelefono: '+57',
        foto: 'https://flagcdn.com/160x120/co.png',
      },
      {
        id: 45,
        nombre: 'Comoras',
        nombrecorto: 'COM',
        codigopais: 'COM',
        codigotelefono: '+269',
        foto: 'https://flagcdn.com/160x120/km.png',
      },
      {
        id: 46,
        nombre: 'Congo (República del)',
        nombrecorto: 'COG',
        codigopais: 'COG',
        codigotelefono: '+242',
        foto: 'https://flagcdn.com/160x120/cg.png',
      },
      {
        id: 47,
        nombre: 'Congo (República Democrática del)',
        nombrecorto: 'COD',
        codigopais: 'COD',
        codigotelefono: '+243',
        foto: 'https://flagcdn.com/160x120/cd.png',
      },
      {
        id: 48,
        nombre: 'Corea del Norte',
        nombrecorto: 'PRK',
        codigopais: 'PRK',
        codigotelefono: '+850',
        foto: 'https://flagcdn.com/160x120/kp.png',
      },
      {
        id: 49,
        nombre: 'Corea del Sur',
        nombrecorto: 'KOR',
        codigopais: 'KOR',
        codigotelefono: '+82',
        foto: 'https://flagcdn.com/160x120/kr.png',
      },
      {
        id: 50,
        nombre: 'Costa de Marfil',
        nombrecorto: 'CIV',
        codigopais: 'CIV',
        codigotelefono: '+225',
        foto: 'https://flagcdn.com/160x120/ci.png',
      },
      {
        id: 51,
        nombre: 'Costa Rica',
        nombrecorto: 'CRI',
        codigopais: 'CRI',
        codigotelefono: '+506',
        foto: 'https://flagcdn.com/160x120/cr.png',
      },
      {
        id: 52,
        nombre: 'Croacia',
        nombrecorto: 'HRV',
        codigopais: 'HRV',
        codigotelefono: '+385',
        foto: 'https://flagcdn.com/160x120/hr.png',
      },
      {
        id: 53,
        nombre: 'Cuba',
        nombrecorto: 'CUB',
        codigopais: 'CUB',
        codigotelefono: '+53',
        foto: 'https://flagcdn.com/160x120/cu.png',
      },
      {
        id: 54,
        nombre: 'Curazao',
        nombrecorto: 'CUW',
        codigopais: 'CUW',
        codigotelefono: '+5999',
        foto: 'https://flagcdn.com/160x120/cw.png',
      },
      {
        id: 55,
        nombre: 'Dinamarca',
        nombrecorto: 'DNK',
        codigopais: 'DNK',
        codigotelefono: '+45',
        foto: 'https://flagcdn.com/160x120/dk.png',
      },
      {
        id: 56,
        nombre: 'Dominica',
        nombrecorto: 'DMA',
        codigopais: 'DMA',
        codigotelefono: '+1 767',
        foto: 'https://flagcdn.com/160x120/dm.png',
      },
      {
        id: 57,
        nombre: 'Ecuador',
        nombrecorto: 'ECU',
        codigopais: 'ECU',
        codigotelefono: '+593',
        foto: 'https://flagcdn.com/160x120/ec.png',
      },
      {
        id: 58,
        nombre: 'Egipto',
        nombrecorto: 'EGY',
        codigopais: 'EGY',
        codigotelefono: '+20',
        foto: 'https://flagcdn.com/160x120/eg.png',
      },
      {
        id: 59,
        nombre: 'El Salvador',
        nombrecorto: 'SLV',
        codigopais: 'SLV',
        codigotelefono: '+503',
        foto: 'https://flagcdn.com/160x120/sv.png',
      },
      {
        id: 60,
        nombre: 'Emiratos Árabes Unidos',
        nombrecorto: 'ARE',
        codigopais: 'ARE',
        codigotelefono: '+971',
        foto: 'https://flagcdn.com/160x120/ae.png',
      }, {
        id: 61,
        nombre: 'Estados Unidos',
        nombrecorto: 'EEUU',
        codigopais: 'USA',
        foto: 'https://flagcdn.com/160x120/us.png'
      },
      {
        id: 62,
        nombre: 'Eritrea',
        nombrecorto: 'ERI',
        codigopais: 'ERI',
        codigotelefono: '+291',
        foto: 'https://flagcdn.com/160x120/er.png',
      },
      {
        id: 63,
        nombre: 'Eslovaquia',
        nombrecorto: 'SVK',
        codigopais: 'SVK',
        codigotelefono: '+421',
        foto: 'https://flagcdn.com/160x120/sk.png',
      },
      {
        id: 64,
        nombre: 'Eslovenia',
        nombrecorto: 'SVN',
        codigopais: 'SVN',
        codigotelefono: '+386',
        foto: 'https://flagcdn.com/160x120/si.png',
      },
      {
        id: 65,
        nombre: 'España',
        nombrecorto: 'ESP',
        codigopais: 'ESP',
        codigotelefono: '+34',
        foto: 'https://flagcdn.com/160x120/es.png',
      },
      {
        id: 66,
        nombre: 'Estonia',
        nombrecorto: 'EST',
        codigopais: 'EST',
        codigotelefono: '+372',
        foto: 'https://flagcdn.com/160x120/ee.png',
      },
      {
        id: 67,
        nombre: 'Etiopía',
        nombrecorto: 'ETH',
        codigopais: 'ETH',
        codigotelefono: '+251',
        foto: 'https://flagcdn.com/160x120/et.png',
      },
      {
        id: 68,
        nombre: 'Filipinas',
        nombrecorto: 'PHL',
        codigopais: 'PHL',
        codigotelefono: '+63',
        foto: 'https://flagcdn.com/160x120/ph.png',
      },
      {
        id: 69,
        nombre: 'Finlandia',
        nombrecorto: 'FIN',
        codigopais: 'FIN',
        codigotelefono: '+358',
        foto: 'https://flagcdn.com/160x120/fi.png',
      },
      {
        id: 70,
        nombre: 'Fiyi',
        nombrecorto: 'FJI',
        codigopais: 'FJI',
        codigotelefono: '+679',
        foto: 'https://flagcdn.com/160x120/fj.png',
      },
      {
        id: 71,
        nombre: 'Francia',
        nombrecorto: 'FRA',
        codigopais: 'FRA',
        codigotelefono: '+33',
        foto: 'https://flagcdn.com/160x120/fr.png',
      },
      {
        id: 72,
        nombre: 'Gabón',
        nombrecorto: 'GAB',
        codigopais: 'GAB',
        codigotelefono: '+241',
        foto: 'https://flagcdn.com/160x120/ga.png',
      },
      {
        id: 73,
        nombre: 'Gambia',
        nombrecorto: 'GMB',
        codigopais: 'GMB',
        codigotelefono: '+220',
        foto: 'https://flagcdn.com/160x120/gm.png',
      },
      {
        id: 74,
        nombre: 'Georgia',
        nombrecorto: 'GEO',
        codigopais: 'GEO',
        codigotelefono: '+995',
        foto: 'https://flagcdn.com/160x120/ge.png',
      },
      {
        id: 75,
        nombre: 'Ghana',
        nombrecorto: 'GHA',
        codigopais: 'GHA',
        codigotelefono: '+233',
        foto: 'https://flagcdn.com/160x120/gh.png',
      },
      {
        id: 76,
        nombre: 'Gibraltar',
        nombrecorto: 'GIB',
        codigopais: 'GIB',
        codigotelefono: '+350',
        foto: 'https://flagcdn.com/160x120/gi.png',
      },
      {
        id: 77,
        nombre: 'Grecia',
        nombrecorto: 'GRC',
        codigopais: 'GRC',
        codigotelefono: '+30',
        foto: 'https://flagcdn.com/160x120/gr.png',
      },
      {
        id: 78,
        nombre: 'Groenlandia',
        nombrecorto: 'GRL',
        codigopais: 'GRL',
        codigotelefono: '+299',
        foto: 'https://flagcdn.com/160x120/gl.png',
      },
      {
        id: 79,
        nombre: 'Granada',
        nombrecorto: 'GRD',
        codigopais: 'GRD',
        codigotelefono: '+1 473',
        foto: 'https://flagcdn.com/160x120/gd.png',
      },
      {
        id: 80,
        nombre: 'Guadalupe',
        nombrecorto: 'GLP',
        codigopais: 'GLP',
        codigotelefono: '+590',
        foto: 'https://flagcdn.com/160x120/gp.png',
      },
      {
        id: 81,
        nombre: 'Guam',
        nombrecorto: 'GUM',
        codigopais: 'GUM',
        codigotelefono: '+1 671',
        foto: 'https://flagcdn.com/160x120/gu.png',
      },
      {
        id: 82,
        nombre: 'Guatemala',
        nombrecorto: 'GTM',
        codigopais: 'GTM',
        codigotelefono: '+502',
        foto: 'https://flagcdn.com/160x120/gt.png',
      },
      {
        id: 83,
        nombre: 'Guayana Francesa',
        nombrecorto: 'GUF',
        codigopais: 'GUF',
        codigotelefono: '+594',
        foto: 'https://flagcdn.com/160x120/gf.png',
      },
      {
        id: 84,
        nombre: 'Guinea',
        nombrecorto: 'GIN',
        codigopais: 'GIN',
        codigotelefono: '+224',
        foto: 'https://flagcdn.com/160x120/gn.png',
      },
      {
        id: 85,
        nombre: 'Guinea Ecuatorial',
        nombrecorto: 'GNQ',
        codigopais: 'GNQ',
        codigotelefono: '+240',
        foto: 'https://flagcdn.com/160x120/gq.png',
      },
      {
        id: 86,
        nombre: 'Guinea-Bisáu',
        nombrecorto: 'GNB',
        codigopais: 'GNB',
        codigotelefono: '+245',
        foto: 'https://flagcdn.com/160x120/gw.png',
      },
      {
        id: 87,
        nombre: 'Guyana',
        nombrecorto: 'GUY',
        codigopais: 'GUY',
        codigotelefono: '+592',
        foto: 'https://flagcdn.com/160x120/gy.png',
      },
      {
        id: 88,
        nombre: 'Haití',
        nombrecorto: 'HTI',
        codigopais: 'HTI',
        codigotelefono: '+509',
        foto: 'https://flagcdn.com/160x120/ht.png',
      },
      {
        id: 89,
        nombre: 'Honduras',
        nombrecorto: 'HND',
        codigopais: 'HND',
        codigotelefono: '+504',
        foto: 'https://flagcdn.com/160x120/hn.png',
      },
      {
        id: 90,
        nombre: 'Hong Kong',
        nombrecorto: 'HKG',
        codigopais: 'HKG',
        codigotelefono: '+852',
        foto: 'https://flagcdn.com/160x120/hk.png',
      },
      {
        id: 91,
        nombre: 'Hungría',
        nombrecorto: 'HUN',
        codigopais: 'HUN',
        codigotelefono: '+36',
        foto: 'https://flagcdn.com/160x120/hu.png',
      },
      {
        id: 92,
        nombre: 'India',
        nombrecorto: 'IND',
        codigopais: 'IND',
        codigotelefono: '+91',
        foto: 'https://flagcdn.com/160x120/in.png',
      },
      {
        id: 93,
        nombre: 'Indonesia',
        nombrecorto: 'IDN',
        codigopais: 'IDN',
        codigotelefono: '+62',
        foto: 'https://flagcdn.com/160x120/id.png',
      },
      {
        id: 94,
        nombre: 'Irán',
        nombrecorto: 'IRN',
        codigopais: 'IRN',
        codigotelefono: '+98',
        foto: 'https://flagcdn.com/160x120/ir.png',
      },
      {
        id: 95,
        nombre: 'Iraq',
        nombrecorto: 'IRQ',
        codigopais: 'IRQ',
        codigotelefono: '+964',
        foto: 'https://flagcdn.com/160x120/iq.png',
      },
      {
        id: 96,
        nombre: 'Irlanda',
        nombrecorto: 'IRL',
        codigopais: 'IRL',
        codigotelefono: '+353',
        foto: 'https://flagcdn.com/160x120/ie.png',
      },
      {
        id: 97,
        nombre: 'Isla Bouvet',
        nombrecorto: 'BVT',
        codigopais: 'BVT',
        codigotelefono: '+47',
        foto: 'https://flagcdn.com/160x120/bv.png',
      },
      {
        id: 98,
        nombre: 'Isla de Man',
        nombrecorto: 'IMN',
        codigopais: 'IMN',
        codigotelefono: '+44',
        foto: 'https://flagcdn.com/160x120/im.png',
      },
      {
        id: 99,
        nombre: 'Isla de Navidad',
        nombrecorto: 'CXR',
        codigopais: 'CXR',
        codigotelefono: '+61',
        foto: 'https://flagcdn.com/160x120/cx.png',
      },
      {
        id: 100,
        nombre: 'Isla Norfolk',
        nombrecorto: 'NFK',
        codigopais: 'NFK',
        codigotelefono: '+672',
        foto: 'https://flagcdn.com/160x120/nf.png',
      },
      {
        id: 101,
        nombre: 'Islandia',
        nombrecorto: 'ISL',
        codigopais: 'ISL',
        codigotelefono: '+354',
        foto: 'https://flagcdn.com/160x120/is.png',
      },
      {
        id: 102,
        nombre: 'Islas Caimán',
        nombrecorto: 'CYM',
        codigopais: 'CYM',
        codigotelefono: '+1 345',
        foto: 'https://flagcdn.com/160x120/ky.png',
      },
      {
        id: 103,
        nombre: 'Islas Cocos (Keeling)',
        nombrecorto: 'CCK',
        codigopais: 'CCK',
        codigotelefono: '+61',
        foto: 'https://flagcdn.com/160x120/cc.png',
      },
      {
        id: 104,
        nombre: 'Islas Cook',
        nombrecorto: 'COK',
        codigopais: 'COK',
        codigotelefono: '+682',
        foto: 'https://flagcdn.com/160x120/ck.png',
      },
      {
        id: 105,
        nombre: 'Islas Feroe',
        nombrecorto: 'FRO',
        codigopais: 'FRO',
        codigotelefono: '+298',
        foto: 'https://flagcdn.com/160x120/fo.png',
      },
      {
        id: 106,
        nombre: 'Islas Georgias del Sur y Sandwich del Sur',
        nombrecorto: 'SGS',
        codigopais: 'SGS',
        codigotelefono: '+500',
        foto: 'https://flagcdn.com/160x120/gs.png',
      },
      {
        id: 107,
        nombre: 'Islas Heard y McDonald',
        nombrecorto: 'HMD',
        codigopais: 'HMD',
        codigotelefono: '+672',
        foto: 'https://flagcdn.com/160x120/hm.png',
      },
      {
        id: 108,
        nombre: 'Islas Malvinas',
        nombrecorto: 'FLK',
        codigopais: 'FLK',
        codigotelefono: '+500',
        foto: 'https://flagcdn.com/160x120/fk.png',
      },
      {
        id: 109,
        nombre: 'Islas Marianas del Norte',
        nombrecorto: 'MNP',
        codigopais: 'MNP',
        codigotelefono: '+1 670',
        foto: 'https://flagcdn.com/160x120/mp.png',
      },
      {
        id: 110,
        nombre: 'Islas Pitcairn',
        nombrecorto: 'PCN',
        codigopais: 'PCN',
        codigotelefono: '+64',
        foto: 'https://flagcdn.com/160x120/pn.png',
      },
      {
        id: 111,
        nombre: 'Islas Salomón',
        nombrecorto: 'SLB',
        codigopais: 'SLB',
        codigotelefono: '+677',
        foto: 'https://flagcdn.com/160x120/sb.png',
      },
      {
        id: 112,
        nombre: 'Islas Turcas y Caicos',
        nombrecorto: 'TCA',
        codigopais: 'TCA',
        codigotelefono: '+1 649',
        foto: 'https://flagcdn.com/160x120/tc.png',
      },
      {
        id: 113,
        nombre: 'Islas Vírgenes Británicas',
        nombrecorto: 'VGB',
        codigopais: 'VGB',
        codigotelefono: '+1 284',
        foto: 'https://flagcdn.com/160x120/vg.png',
      },
      {
        id: 114,
        nombre: 'Islas Vírgenes de los Estados Unidos',
        nombrecorto: 'VIR',
        codigopais: 'VIR',
        codigotelefono: '+1 340',
        foto: 'https://flagcdn.com/160x120/vi.png',
      },
      {
        id: 115,
        nombre: 'Israel',
        nombrecorto: 'ISR',
        codigopais: 'ISR',
        codigotelefono: '+972',
        foto: 'https://flagcdn.com/160x120/il.png',
      },
      {
        id: 116,
        nombre: 'Italia',
        nombrecorto: 'ITA',
        codigopais: 'ITA',
        codigotelefono: '+39',
        foto: 'https://flagcdn.com/160x120/it.png',
      },
      {
        id: 117,
        nombre: 'Jamaica',
        nombrecorto: 'JAM',
        codigopais: 'JAM',
        codigotelefono: '+1 876',
        foto: 'https://flagcdn.com/160x120/jm.png',
      },
      {
        id: 118,
        nombre: 'Japón',
        nombrecorto: 'JPN',
        codigopais: 'JPN',
        codigotelefono: '+81',
        foto: 'https://flagcdn.com/160x120/jp.png',
      },
      {
        id: 119,
        nombre: 'Jordania',
        nombrecorto: 'JOR',
        codigopais: 'JOR',
        codigotelefono: '+962',
        foto: 'https://flagcdn.com/160x120/jo.png',
      },
      {
        id: 120,
        nombre: 'Kazajistán',
        nombrecorto: 'KAZ',
        codigopais: 'KAZ',
        codigotelefono: '+7',
        foto: 'https://flagcdn.com/160x120/kz.png',
      },
      {
        id: 121,
        nombre: 'Kenia',
        nombrecorto: 'KEN',
        codigopais: 'KEN',
        codigotelefono: '+254',
        foto: 'https://flagcdn.com/160x120/ke.png',
      },
      {
        id: 122,
        nombre: 'Kirguistán',
        nombrecorto: 'KGZ',
        codigopais: 'KGZ',
        codigotelefono: '+996',
        foto: 'https://flagcdn.com/160x120/kg.png',
      },
      {
        id: 123,
        nombre: 'Kiribati',
        nombrecorto: 'KIR',
        codigopais: 'KIR',
        codigotelefono: '+686',
        foto: 'https://flagcdn.com/160x120/ki.png',
      },
      {
        id: 124,
        nombre: 'Kuwait',
        nombrecorto: 'KWT',
        codigopais: 'KWT',
        codigotelefono: '+965',
        foto: 'https://flagcdn.com/160x120/kw.png',
      },
      {
        id: 125,
        nombre: 'Laos',
        nombrecorto: 'LAO',
        codigopais: 'LAO',
        codigotelefono: '+856',
        foto: 'https://flagcdn.com/160x120/la.png',
      },
      {
        id: 126,
        nombre: 'Lesoto',
        nombrecorto: 'LSO',
        codigopais: 'LSO',
        codigotelefono: '+266',
        foto: 'https://flagcdn.com/160x120/ls.png',
      },
      {
        id: 127,
        nombre: 'Letonia',
        nombrecorto: 'LVA',
        codigopais: 'LVA',
        codigotelefono: '+371',
        foto: 'https://flagcdn.com/160x120/lv.png',
      },
      {
        id: 128,
        nombre: 'Líbano',
        nombrecorto: 'LBN',
        codigopais: 'LBN',
        codigotelefono: '+961',
        foto: 'https://flagcdn.com/160x120/lb.png',
      },
      {
        id: 129,
        nombre: 'Liberia',
        nombrecorto: 'LBR',
        codigopais: 'LBR',
        codigotelefono: '+231',
        foto: 'https://flagcdn.com/160x120/lr.png',
      },
      {
        id: 130,
        nombre: 'Libia',
        nombrecorto: 'LBY',
        codigopais: 'LBY',
        codigotelefono: '+218',
        foto: 'https://flagcdn.com/160x120/ly.png',
      },
      {
        id: 131,
        nombre: 'Liechtenstein',
        nombrecorto: 'LIE',
        codigopais: 'LIE',
        codigotelefono: '+423',
        foto: 'https://flagcdn.com/160x120/li.png',
      },
      {
        id: 132,
        nombre: 'Lituania',
        nombrecorto: 'LTU',
        codigopais: 'LTU',
        codigotelefono: '+370',
        foto: 'https://flagcdn.com/160x120/lt.png',
      },
      {
        id: 133,
        nombre: 'Luxemburgo',
        nombrecorto: 'LUX',
        codigopais: 'LUX',
        codigotelefono: '+352',
        foto: 'https://flagcdn.com/160x120/lu.png',
      },
      {
        id: 134,
        nombre: 'Macao',
        nombrecorto: 'MAC',
        codigopais: 'MAC',
        codigotelefono: '+853',
        foto: 'https://flagcdn.com/160x120/mo.png',
      },
      {
        id: 135,
        nombre: 'Macedonia del Norte',
        nombrecorto: 'MKD',
        codigopais: 'MKD',
        codigotelefono: '+389',
        foto: 'https://flagcdn.com/160x120/mk.png',
      },
      {
        id: 136,
        nombre: 'Madagascar',
        nombrecorto: 'MDG',
        codigopais: 'MDG',
        codigotelefono: '+261',
        foto: 'https://flagcdn.com/160x120/mg.png',
      },
      {
        id: 137,
        nombre: 'Malasia',
        nombrecorto: 'MYS',
        codigopais: 'MYS',
        codigotelefono: '+60',
        foto: 'https://flagcdn.com/160x120/my.png',
      },
      {
        id: 138,
        nombre: 'Malawi',
        nombrecorto: 'MWI',
        codigopais: 'MWI',
        codigotelefono: '+265',
        foto: 'https://flagcdn.com/160x120/mw.png',
      },
      {
        id: 139,
        nombre: 'Maldivas',
        nombrecorto: 'MDV',
        codigopais: 'MDV',
        codigotelefono: '+960',
        foto: 'https://flagcdn.com/160x120/mv.png',
      },
      {
        id: 140,
        nombre: 'Malí',
        nombrecorto: 'MLI',
        codigopais: 'MLI',
        codigotelefono: '+223',
        foto: 'https://flagcdn.com/160x120/ml.png',
      },
      {
        id: 141,
        nombre: 'Malta',
        nombrecorto: 'MLT',
        codigopais: 'MLT',
        codigotelefono: '+356',
        foto: 'https://flagcdn.com/160x120/mt.png',
      },
      {
        id: 142,
        nombre: 'Marruecos',
        nombrecorto: 'MAR',
        codigopais: 'MAR',
        codigotelefono: '+212',
        foto: 'https://flagcdn.com/160x120/ma.png',
      },
      {
        id: 143,
        nombre: 'Martinica',
        nombrecorto: 'MTQ',
        codigopais: 'MTQ',
        codigotelefono: '+596',
        foto: 'https://flagcdn.com/160x120/mq.png',
      },
      {
        id: 144,
        nombre: 'Mauricio',
        nombrecorto: 'MUS',
        codigopais: 'MUS',
        codigotelefono: '+230',
        foto: 'https://flagcdn.com/160x120/mu.png',
      },
      {
        id: 145,
        nombre: 'Mauritania',
        nombrecorto: 'MRT',
        codigopais: 'MRT',
        codigotelefono: '+222',
        foto: 'https://flagcdn.com/160x120/mr.png',
      },
      {
        id: 146,
        nombre: 'Mayotte',
        nombrecorto: 'MYT',
        codigopais: 'MYT',
        codigotelefono: '+262',
        foto: 'https://flagcdn.com/160x120/yt.png',
      },
      {
        id: 147,
        nombre: 'Micronesia',
        nombrecorto: 'FSM',
        codigopais: 'FSM',
        codigotelefono: '+691',
        foto: 'https://flagcdn.com/160x120/fm.png',
      },
      {
        id: 148,
        nombre: 'México',
        nombrecorto: 'MX',
        codigopais: 'MEX',
        codigotelefono: '+52',
        foto: 'https://flagcdn.com/160x120/mx.png',
      },
      {
        id: 149,
        nombre: 'Moldavia',
        nombrecorto: 'MDA',
        codigopais: 'MDA',
        codigotelefono: '+373',
        foto: 'https://flagcdn.com/160x120/md.png',
      },
      {
        id: 150,
        nombre: 'Mónaco',
        nombrecorto: 'MCO',
        codigopais: 'MCO',
        codigotelefono: '+377',
        foto: 'https://flagcdn.com/160x120/mc.png',
      },
      {
        id: 151,
        nombre: 'Mongolia',
        nombrecorto: 'MNG',
        codigopais: 'MNG',
        codigotelefono: '+976',
        foto: 'https://flagcdn.com/160x120/mn.png',
      },

      {
        id: 153,
        nombre: 'Montenegro',
        nombrecorto: 'MNE',
        codigopais: 'MNE',
        codigotelefono: '+382',
        foto: 'https://flagcdn.com/160x120/me.png',
      },
      {
        id: 154,
        nombre: 'Montserrat',
        nombrecorto: 'MSR',
        codigopais: 'MSR',
        codigotelefono: '+1 664',
        foto: 'https://flagcdn.com/160x120/ms.png',
      },
      {
        id: 155,
        nombre: 'Mozambique',
        nombrecorto: 'MOZ',
        codigopais: 'MOZ',
        codigotelefono: '+258',
        foto: 'https://flagcdn.com/160x120/mz.png',
      },
      {
        id: 156,
        nombre: 'Myanmar',
        nombrecorto: 'MMR',
        codigopais: 'MMR',
        codigotelefono: '+95',
        foto: 'https://flagcdn.com/160x120/mm.png',
      },
      {
        id: 157,
        nombre: 'Namibia',
        nombrecorto: 'NAM',
        codigopais: 'NAM',
        codigotelefono: '+264',
        foto: 'https://flagcdn.com/160x120/na.png',
      },
      {
        id: 158,
        nombre: 'Nauru',
        nombrecorto: 'NRU',
        codigopais: 'NRU',
        codigotelefono: '+674',
        foto: 'https://flagcdn.com/160x120/nr.png',
      },
      {
        id: 159,
        nombre: 'Nepal',
        nombrecorto: 'NPL',
        codigopais: 'NPL',
        codigotelefono: '+977',
        foto: 'https://flagcdn.com/160x120/np.png',
      },
      {
        id: 160,
        nombre: 'Nicaragua',
        nombrecorto: 'NIC',
        codigopais: 'NIC',
        codigotelefono: '+505',
        foto: 'https://flagcdn.com/160x120/ni.png',
      },
      {
        id: 161,
        nombre: 'Níger',
        nombrecorto: 'NER',
        codigopais: 'NER',
        codigotelefono: '+227',
        foto: 'https://flagcdn.com/160x120/ne.png',
      },
      {
        id: 162,
        nombre: 'Nigeria',
        nombrecorto: 'NGA',
        codigopais: 'NGA',
        codigotelefono: '+234',
        foto: 'https://flagcdn.com/160x120/ng.png',
      },
      {
        id: 163,
        nombre: 'Niue',
        nombrecorto: 'NIU',
        codigopais: 'NIU',
        codigotelefono: '+683',
        foto: 'https://flagcdn.com/160x120/nu.png',
      },
      {
        id: 164,
        nombre: 'Noruega',
        nombrecorto: 'NOR',
        codigopais: 'NOR',
        codigotelefono: '+47',
        foto: 'https://flagcdn.com/160x120/no.png',
      },
      {
        id: 165,
        nombre: 'Nueva Caledonia',
        nombrecorto: 'NCL',
        codigopais: 'NCL',
        codigotelefono: '+687',
        foto: 'https://flagcdn.com/160x120/nc.png',
      },
      {
        id: 166,
        nombre: 'Nueva Zelanda',
        nombrecorto: 'NZL',
        codigopais: 'NZL',
        codigotelefono: '+64',
        foto: 'https://flagcdn.com/160x120/nz.png',
      },
      {
        id: 167,
        nombre: 'Omán',
        nombrecorto: 'OMN',
        codigopais: 'OMN',
        codigotelefono: '+968',
        foto: 'https://flagcdn.com/160x120/om.png',
      },
      {
        id: 168,
        nombre: 'Países Bajos',
        nombrecorto: 'NLD',
        codigopais: 'NLD',
        codigotelefono: '+31',
        foto: 'https://flagcdn.com/160x120/nl.png',
      },
      {
        id: 169,
        nombre: 'Pakistán',
        nombrecorto: 'PAK',
        codigopais: 'PAK',
        codigotelefono: '+92',
        foto: 'https://flagcdn.com/160x120/pk.png',
      },
      {
        id: 170,
        nombre: 'Palau',
        nombrecorto: 'PLW',
        codigopais: 'PLW',
        codigotelefono: '+680',
        foto: 'https://flagcdn.com/160x120/pw.png',
      },
      {
        id: 171,
        nombre: 'Palestina',
        nombrecorto: 'PSE',
        codigopais: 'PSE',
        codigotelefono: '+970',
        foto: 'https://flagcdn.com/160x120/ps.png',
      },
      {
        id: 172,
        nombre: 'Panamá',
        nombrecorto: 'PAN',
        codigopais: 'PAN',
        codigotelefono: '+507',
        foto: 'https://flagcdn.com/160x120/pa.png',
      },
      {
        id: 173,
        nombre: 'Papúa Nueva Guinea',
        nombrecorto: 'PNG',
        codigopais: 'PNG',
        codigotelefono: '+675',
        foto: 'https://flagcdn.com/160x120/pg.png',
      },
      {
        id: 174,
        nombre: 'Paraguay',
        nombrecorto: 'PRY',
        codigopais: 'PRY',
        codigotelefono: '+595',
        foto: 'https://flagcdn.com/160x120/py.png',
      },
      {
        id: 175,
        nombre: 'Perú',
        nombrecorto: 'PER',
        codigopais: 'PER',
        codigotelefono: '+51',
        foto: 'https://flagcdn.com/160x120/pe.png',
      },
      {
        id: 176,
        nombre: 'Polinesia Francesa',
        nombrecorto: 'PYF',
        codigopais: 'PYF',
        codigotelefono: '+689',
        foto: 'https://flagcdn.com/160x120/pf.png',
      },
      {
        id: 177,
        nombre: 'Polonia',
        nombrecorto: 'POL',
        codigopais: 'POL',
        codigotelefono: '+48',
        foto: 'https://flagcdn.com/160x120/pl.png',
      },
      {
        id: 178,
        nombre: 'Portugal',
        nombrecorto: 'PRT',
        codigopais: 'PRT',
        codigotelefono: '+351',
        foto: 'https://flagcdn.com/160x120/pt.png',
      },
      {
        id: 179,
        nombre: 'Puerto Rico',
        nombrecorto: 'PRI',
        codigopais: 'PRI',
        codigotelefono: '+1 787',
        foto: 'https://flagcdn.com/160x120/pr.png',
      },
      {
        id: 180,
        nombre: 'Qatar',
        nombrecorto: 'QAT',
        codigopais: 'QAT',
        codigotelefono: '+974',
        foto: 'https://flagcdn.com/160x120/qa.png',
      },
      {
        id: 181,
        nombre: 'Reino Unido',
        nombrecorto: 'GBR',
        codigopais: 'GBR',
        codigotelefono: '+44',
        foto: 'https://flagcdn.com/160x120/gb.png',
      },
      {
        id: 182,
        nombre: 'República Centroafricana',
        nombrecorto: 'CAF',
        codigopais: 'CAF',
        codigotelefono: '+236',
        foto: 'https://flagcdn.com/160x120/cf.png',
      },
      {
        id: 183,
        nombre: 'República Checa',
        nombrecorto: 'CZE',
        codigopais: 'CZE',
        codigotelefono: '+420',
        foto: 'https://flagcdn.com/160x120/cz.png',
      },
      {
        id: 184,
        nombre: 'República Dominicana',
        nombrecorto: 'DOM',
        codigopais: 'DOM',
        codigotelefono: '+1 809',
        foto: 'https://flagcdn.com/160x120/do.png',
      },
      {
        id: 185,
        nombre: 'Reunión',
        nombrecorto: 'REU',
        codigopais: 'REU',
        codigotelefono: '+262',
        foto: 'https://flagcdn.com/160x120/re.png',
      },
      {
        id: 186,
        nombre: 'Ruanda',
        nombrecorto: 'RWA',
        codigopais: 'RWA',
        codigotelefono: '+250',
        foto: 'https://flagcdn.com/160x120/rw.png',
      },
      {
        id: 187,
        nombre: 'Rumania',
        nombrecorto: 'ROU',
        codigopais: 'ROU',
        codigotelefono: '+40',
        foto: 'https://flagcdn.com/160x120/ro.png',
      },
      {
        id: 188,
        nombre: 'Rusia',
        nombrecorto: 'RUS',
        codigopais: 'RUS',
        codigotelefono: '+7',
        foto: 'https://flagcdn.com/160x120/ru.png',
      },
      {
        id: 189,
        nombre: 'Sahara Occidental',
        nombrecorto: 'ESH',
        codigopais: 'ESH',
        codigotelefono: '+212',
        foto: 'https://flagcdn.com/160x120/eh.png',
      },
      {
        id: 190,
        nombre: 'Samoa',
        nombrecorto: 'WSM',
        codigopais: 'WSM',
        codigotelefono: '+685',
        foto: 'https://flagcdn.com/160x120/ws.png',
      },
      {
        id: 191,
        nombre: 'Samoa Americana',
        nombrecorto: 'ASM',
        codigopais: 'ASM',
        codigotelefono: '+1 684',
        foto: 'https://flagcdn.com/160x120/as.png',
      },
      {
        id: 192,
        nombre: 'San Bartolomé',
        nombrecorto: 'BLM',
        codigopais: 'BLM',
        codigotelefono: '+590',
        foto: 'https://flagcdn.com/160x120/bl.png',
      },
      {
        id: 193,
        nombre: 'San Cristóbal y Nieves',
        nombrecorto: 'KNA',
        codigopais: 'KNA',
        codigotelefono: '+1 869',
        foto: 'https://flagcdn.com/160x120/kn.png',
      },
      {
        id: 194,
        nombre: 'San Marino',
        nombrecorto: 'SMR',
        codigopais: 'SMR',
        codigotelefono: '+378',
        foto: 'https://flagcdn.com/160x120/sm.png',
      },
      {
        id: 195,
        nombre: 'San Martín (parte francesa)',
        nombrecorto: 'MAF',
        codigopais: 'MAF',
        codigotelefono: '+590',
        foto: 'https://flagcdn.com/160x120/mf.png',
      },
      {
        id: 196,
        nombre: 'San Pedro y Miquelón',
        nombrecorto: 'SPM',
        codigopais: 'SPM',
        codigotelefono: '+508',
        foto: 'https://flagcdn.com/160x120/pm.png',
      },
      {
        id: 197,
        nombre: 'San Vicente y las Granadinas',
        nombrecorto: 'VCT',
        codigopais: 'VCT',
        codigotelefono: '+1 784',
        foto: 'https://flagcdn.com/160x120/vc.png',
      },
      {
        id: 198,
        nombre: 'Santa Elena, Ascensión y Tristán de Acuña',
        nombrecorto: 'SHN',
        codigopais: 'SHN',
        codigotelefono: '+290',
        foto: 'https://flagcdn.com/160x120/sh.png',
      },
      {
        id: 199,
        nombre: 'Santa Lucía',
        nombrecorto: 'LCA',
        codigopais: 'LCA',
        codigotelefono: '+1 758',
        foto: 'https://flagcdn.com/160x120/lc.png',
      },
      {
        id: 200,
        nombre: 'Santo Tomé y Príncipe',
        nombrecorto: 'STP',
        codigopais: 'STP',
        codigotelefono: '+239',
        foto: 'https://flagcdn.com/160x120/st.png',
      },
      {
        id: 201,
        nombre: 'Senegal',
        nombrecorto: 'SEN',
        codigopais: 'SEN',
        codigotelefono: '+221',
        foto: 'https://flagcdn.com/160x120/sn.png',
      },
      {
        id: 202,
        nombre: 'Serbia',
        nombrecorto: 'SRB',
        codigopais: 'SRB',
        codigotelefono: '+381',
        foto: 'https://flagcdn.com/160x120/rs.png',
      },
      {
        id: 203,
        nombre: 'Seychelles',
        nombrecorto: 'SYC',
        codigopais: 'SYC',
        codigotelefono: '+248',
        foto: 'https://flagcdn.com/160x120/sc.png',
      },
      {
        id: 204,
        nombre: 'Sierra Leona',
        nombrecorto: 'SLE',
        codigopais: 'SLE',
        codigotelefono: '+232',
        foto: 'https://flagcdn.com/160x120/sl.png',
      },
      {
        id: 205,
        nombre: 'Singapur',
        nombrecorto: 'SGP',
        codigopais: 'SGP',
        codigotelefono: '+65',
        foto: 'https://flagcdn.com/160x120/sg.png',
      },
      {
        id: 206,
        nombre: 'Sint Maarten (parte neerlandesa)',
        nombrecorto: 'SXM',
        codigopais: 'SXM',
        codigotelefono: '+1 721',
        foto: 'https://flagcdn.com/160x120/sx.png',
      },
      {
        id: 207,
        nombre: 'Siria',
        nombrecorto: 'SYR',
        codigopais: 'SYR',
        codigotelefono: '+963',
        foto: 'https://flagcdn.com/160x120/sy.png',
      },
      {
        id: 208,
        nombre: 'Somalia',
        nombrecorto: 'SOM',
        codigopais: 'SOM',
        codigotelefono: '+252',
        foto: 'https://flagcdn.com/160x120/so.png',
      },
      {
        id: 209,
        nombre: 'Sri Lanka',
        nombrecorto: 'LKA',
        codigopais: 'LKA',
        codigotelefono: '+94',
        foto: 'https://flagcdn.com/160x120/lk.png',
      },
      {
        id: 210,
        nombre: 'Suazilandia',
        nombrecorto: 'SWZ',
        codigopais: 'SWZ',
        codigotelefono: '+268',
        foto: 'https://flagcdn.com/160x120/sz.png',
      },
      {
        id: 211,
        nombre: 'Sudáfrica',
        nombrecorto: 'ZAF',
        codigopais: 'ZAF',
        codigotelefono: '+27',
        foto: 'https://flagcdn.com/160x120/za.png',
      },
      {
        id: 212,
        nombre: 'Sudán',
        nombrecorto: 'SDN',
        codigopais: 'SDN',
        codigotelefono: '+249',
        foto: 'https://flagcdn.com/160x120/sd.png',
      },
      {
        id: 213,
        nombre: 'Sudán del Sur',
        nombrecorto: 'SSD',
        codigopais: 'SSD',
        codigotelefono: '+211',
        foto: 'https://flagcdn.com/160x120/ss.png',
      },
      {
        id: 214,
        nombre: 'Suecia',
        nombrecorto: 'SWE',
        codigopais: 'SWE',
        codigotelefono: '+46',
        foto: 'https://flagcdn.com/160x120/se.png',
      },
      {
        id: 215,
        nombre: 'Suiza',
        nombrecorto: 'CHE',
        codigopais: 'CHE',
        codigotelefono: '+41',
        foto: 'https://flagcdn.com/160x120/ch.png',
      },
      {
        id: 216,
        nombre: 'Surinam',
        nombrecorto: 'SUR',
        codigopais: 'SUR',
        codigotelefono: '+597',
        foto: 'https://flagcdn.com/160x120/sr.png',
      },
      {
        id: 217,
        nombre: 'Svalbard y Jan Mayen',
        nombrecorto: 'SJM',
        codigopais: 'SJM',
        codigotelefono: '+47',
        foto: 'https://flagcdn.com/160x120/sj.png',
      },
      {
        id: 218,
        nombre: 'Tailandia',
        nombrecorto: 'THA',
        codigopais: 'THA',
        codigotelefono: '+66',
        foto: 'https://flagcdn.com/160x120/th.png',
      },
      {
        id: 219,
        nombre: 'Taiwán',
        nombrecorto: 'TWN',
        codigopais: 'TWN',
        codigotelefono: '+886',
        foto: 'https://flagcdn.com/160x120/tw.png',
      },
      {
        id: 220,
        nombre: 'Tanzania',
        nombrecorto: 'TZA',
        codigopais: 'TZA',
        codigotelefono: '+255',
        foto: 'https://flagcdn.com/160x120/tz.png',
      },
      {
        id: 221,
        nombre: 'Tayikistán',
        nombrecorto: 'TJK',
        codigopais: 'TJK',
        codigotelefono: '+992',
        foto: 'https://flagcdn.com/160x120/tj.png',
      },
      {
        id: 222,
        nombre: 'Territorio Británico del Océano Índico',
        nombrecorto: 'IOT',
        codigopais: 'IOT',
        codigotelefono: '+246',
        foto: 'https://flagcdn.com/160x120/io.png',
      },
      {
        id: 223,
        nombre: 'Territorios Australes y Antárticos Franceses',
        nombrecorto: 'ATF',
        codigopais: 'ATF',
        codigotelefono: '+262',
        foto: 'https://flagcdn.com/160x120/tf.png',
      },
      {
        id: 224,
        nombre: 'Timor Oriental',
        nombrecorto: 'TLS',
        codigopais: 'TLS',
        codigotelefono: '+670',
        foto: 'https://flagcdn.com/160x120/tl.png',
      },
      {
        id: 225,
        nombre: 'Togo',
        nombrecorto: 'TGO',
        codigopais: 'TGO',
        codigotelefono: '+228',
        foto: 'https://flagcdn.com/160x120/tg.png',
      },
      {
        id: 226,
        nombre: 'Tokelau',
        nombrecorto: 'TKL',
        codigopais: 'TKL',
        codigotelefono: '+690',
        foto: 'https://flagcdn.com/160x120/tk.png',
      },
      {
        id: 227,
        nombre: 'Tonga',
        nombrecorto: 'TON',
        codigopais: 'TON',
        codigotelefono: '+676',
        foto: 'https://flagcdn.com/160x120/to.png',
      },
      {
        id: 228,
        nombre: 'Trinidad y Tobago',
        nombrecorto: 'TTO',
        codigopais: 'TTO',
        codigotelefono: '+1 868',
        foto: 'https://flagcdn.com/160x120/tt.png',
      },
      {
        id: 229,
        nombre: 'Túnez',
        nombrecorto: 'TUN',
        codigopais: 'TUN',
        codigotelefono: '+216',
        foto: 'https://flagcdn.com/160x120/tn.png',
      },
      {
        id: 230,
        nombre: 'Turkmenistán',
        nombrecorto: 'TKM',
        codigopais: 'TKM',
        codigotelefono: '+993',
        foto: 'https://flagcdn.com/160x120/tm.png',
      },
      {
        id: 231,
        nombre: 'Turquía',
        nombrecorto: 'TUR',
        codigopais: 'TUR',
        codigotelefono: '+90',
        foto: 'https://flagcdn.com/160x120/tr.png',
      },
      {
        id: 232,
        nombre: 'Tuvalu',
        nombrecorto: 'TUV',
        codigopais: 'TUV',
        codigotelefono: '+688',
        foto: 'https://flagcdn.com/160x120/tv.png',
      },
      {
        id: 233,
        nombre: 'Ucrania',
        nombrecorto: 'UKR',
        codigopais: 'UKR',
        codigotelefono: '+380',
        foto: 'https://flagcdn.com/160x120/ua.png',
      },
      {
        id: 234,
        nombre: 'Uganda',
        nombrecorto: 'UGA',
        codigopais: 'UGA',
        codigotelefono: '+256',
        foto: 'https://flagcdn.com/160x120/ug.png',
      },
      {
        id: 235,
        nombre: 'Uruguay',
        nombrecorto: 'URY',
        codigopais: 'URY',
        codigotelefono: '+598',
        foto: 'https://flagcdn.com/160x120/uy.png',
      },
      {
        id: 236,
        nombre: 'Uzbekistán',
        nombrecorto: 'UZB',
        codigopais: 'UZB',
        codigotelefono: '+998',
        foto: 'https://flagcdn.com/160x120/uz.png',
      },
      {
        id: 237,
        nombre: 'Vanuatu',
        nombrecorto: 'VUT',
        codigopais: 'VUT',
        codigotelefono: '+678',
        foto: 'https://flagcdn.com/160x120/vu.png',
      },
      {
        id: 238,
        nombre: 'Venezuela',
        nombrecorto: 'VEN',
        codigopais: 'VEN',
        codigotelefono: '+58',
        foto: 'https://flagcdn.com/160x120/ve.png',
      },
      {
        id: 239,
        nombre: 'Vietnam',
        nombrecorto: 'VNM',
        codigopais: 'VNM',
        codigotelefono: '+84',
        foto: 'https://flagcdn.com/160x120/vn.png',
      },
      {
        id: 240,
        nombre: 'Wallis y Futuna',
        nombrecorto: 'WLF',
        codigopais: 'WLF',
        codigotelefono: '+681',
        foto: 'https://flagcdn.com/160x120/wf.png',
      },
      {
        id: 241,
        nombre: 'Yemen',
        nombrecorto: 'YEM',
        codigopais: 'YEM',
        codigotelefono: '+967',
        foto: 'https://flagcdn.com/160x120/ye.png',
      },
      {
        id: 242,
        nombre: 'Yibuti',
        nombrecorto: 'DJI',
        codigopais: 'DJI',
        codigotelefono: '+253',
        foto: 'https://flagcdn.com/160x120/dj.png',
      },
      {
        id: 243,
        nombre: 'Zambia',
        nombrecorto: 'ZMB',
        codigopais: 'ZMB',
        codigotelefono: '+260',
        foto: 'https://flagcdn.com/160x120/zm.png',
      },
      {
        id: 244,
        nombre: 'Zimbabue',
        nombrecorto: 'ZWE',
        codigopais: 'ZWE',
        codigotelefono: '+263',
        foto: 'https://flagcdn.com/160x120/zw.png',
      },
    ];
    await this.paisRepository.save(paises);
  }

  private async seedAdminUser() {
    const adminUsuario = this.usuarioRepository.create({
      id: 1,
      correo: 'admin@pruebas.com',
      username: 'admin',
      password: await bcrypt.hash('admin123', 10),
      id_rol: 1,
      estatus: true,
    });
    await this.usuarioRepository.save(adminUsuario);

    const adminDetalle = this.usuarioDetalleRepository.create({
      nombres: 'Administrador',
      apellidos: '',
      foto: '/public/images/users/default.png',
      id_pais: 148,
      telefono: '1234567890',
      fecha_nacimiento: new Date('2000-01-01'),
      id_genero: 3,
      id: adminUsuario.id,
    });
    await this.usuarioDetalleRepository.save(adminDetalle);
  }

  private async seedTiposReportes() {
    const reportes = [{
      id: 1,
      nombre: "Reporte de tareas"
    }]
    await this.tipoReportes.save(reportes);
  }
}
